// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Content struct {
	ID    *string `json:"id"`
	Title *string `json:"title"`
	Teams []*Team `json:"teams"`
	Score *int    `json:"score"`
}

type Root struct {
	ID       *string    `json:"id"`
	Title    *string    `json:"title"`
	Segments []*Segment `json:"segments"`
}

type Segment struct {
	ID       *string    `json:"id"`
	Contents []*Content `json:"contents"`
}

type Team struct {
	Name *string `json:"name"`
}
