// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Content interface {
	IsContent()
	GetID() *string
	GetTitle() *string
}

type A struct {
	ID    *string `json:"id"`
	Title *string `json:"title"`
	Teams []*Team `json:"teams"`
}

func (A) IsContent()             {}
func (this A) GetID() *string    { return this.ID }
func (this A) GetTitle() *string { return this.Title }

type B struct {
	ID    *string `json:"id"`
	Title *string `json:"title"`
	Score *int    `json:"score"`
}

func (B) IsContent()             {}
func (this B) GetID() *string    { return this.ID }
func (this B) GetTitle() *string { return this.Title }

type Root struct {
	ID       *string    `json:"id"`
	Title    *string    `json:"title"`
	Segments []*Segment `json:"segments"`
}

type Segment struct {
	ID       *string   `json:"id"`
	Contents []Content `json:"contents"`
}

type Team struct {
	Name *string `json:"name"`
}
